### ISSUE TITLE
Revisar alcance

### ISSUE THREAD

**Issue by adrianmeca** [la-noche/DSW_TP_E-sports#1]
https://github.com/la-noche/DSW_TP_E-sports/blob/4bfab652a5a8896acdb0190a8f7c0a3b26ffbd68/README.md?plain=1#L29-L48

1. el crud de equipo es dependiente porque necesita el usuario que lo crea, pueden dejarlo en el alcance por falta de otro simple pero para la siguiente entrega les conviene empezar por uno más simpleo como tipo juego
2. el alta de equipos es un crud dependiente no un CUU/Epic, necesitan 1 más para regularidad puede ser cancelar la inscripción (con alguna restricción por ejemplo dentro de las 24 hs)
3. el alta de usuarios no es un CUU/Epic para AD necesitarían agregar más alcance por ejemplo de acuerdo a como funcionen los torneos registrar juegos, competencias, resultados de partidas de los equipos, enviar recordatorios, registrar comentarios, etc

**Comment by LeoCarovana** [comment]
Buenos días profe, puede revisar lo que estuvimos corrigiendo sobre nuestro
alcance? Gracias.
